spring:
  config:
    activate:
      on-profile: "prod"

cards:
  message: "Welcome to Khalees2 Cards related APIs in Production environment"
  contactDetails:
    name: "Salman Khaleel Sab - Product Owner"
    email: "salmank7640@gmail.com"
  onCallSupport:
    - 4546546231
    - 1111111111