loans:
  message: "Welcome to Khalees2 Loans related APIs in Testing environment"
  contactDetails:
    name: "Salman Khaleel Sab - QA Lead"
    email: "salmank7640@gmail.com"
  onCallSupport:
    - 4546546231
    - 1111111111